### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by YuanLiXiong** [fengyang0317/unsupervised_captioning#9]
(py36) XXX@lthpc:~/XSpace/Games/ICP1_unsupervised_captioning$ python preprocessing/crawl_descriptions.py
Traceback (most recent call last):
  File "preprocessing/crawl_descriptions.py", line 100, in <module>
    app.run(main)
  File "/home/XXX/miniconda3/envs/py36/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/XXX/miniconda3/envs/py36/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "preprocessing/crawl_descriptions.py", line 96, in main
    download(FLAGS.data_dir, FLAGS.num_pages, i, c)
  File "preprocessing/crawl_descriptions.py", line 76, in download
    all_pages = get_num_pages(label)
  File "preprocessing/crawl_descriptions.py", line 60, in get_num_pages
    num_pages = int(obj.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by YuanLiXiong** [comment]
hello, anyone can help me?

**Comment by fengyang0317** [comment]
Duplicated with #8
